# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'json'
require 'active_collab'

TEST_API_RESPONSES = ENV['TEST_API']

if (TEST_API_RESPONSES)
  puts "TEST_API_RESPONSES variable set. Loading configuration file to test ActiveCollab API." 
  # Load the configuration file
  config_file = File.open(File.join(File.dirname(File.expand_path(__FILE__)), "config", "client.yml"))
  CONFIG = YAML.load(config_file)
  puts "Loaded this config: \n #{JSON.pretty_generate(JSON.parse(CONFIG.to_json))} \n\n"

  # Set some constants
  API_URL = CONFIG['client']['api_url']
  API_KEY = CONFIG['client']['api_key']
else
  puts "TEST_API_RESPONSES variable was not set. Skipping API tests."
  API_URL = "phony.com"
  API_KEY = "baloney"
end

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

